### ISSUE TITLE
Have some questions about the code and please help me!

### ISSUE THREAD

**Issue by ZHANGHE24** [awslabs/s2n-bignum#1]
Hello. I chose a .ml file as an example and I have some problem when I read it. (link: [https://github.com/awslabs/s2n-bignum/blob/e135d896544a0d63b7bed74675216d7f36d76aa8/x86/proofs/bignum_even.ml](url))
I cannot find these key_word (W64_GEN_TAC， X86_SIM_TAC， ENSURES_INIT_TAC， X86_STEPS_TAC， WORD_REDUCE_CONV) in the reference ([https://www.cl.cam.ac.uk/~jrh13/hol-light/reference.html](url)), so I want to know why, maybe the newest version reference I didn't find.
and another question:
in file's line 46:
`(\s. read RIP s = word(pc + 0x12) /\`
how did the number '0x12' come about?  I have no idea about it. (T⌓T)
If you have free time, please help me, thank you very much.

**Comment by jargh** [comment]
You are right that there are prerequisites beyond the HOL Light basics, but these should all be in this repo in the "common" and then "arm" or "x86" as appropriate subdirectories. For example "x86/proofs/base.ml" shows the sequence to load all these prerequisites.

Usually proofs are done first for a "core" function without the saving and restoring of additional registers and then the outer part is added at the end. In this example the core function ends at pc + 0x12, which is where the final return statement is. In more complicated cases there may be restoring of registers and other stack manipulations. You could get this number looking at the length of the formal definition or just by other tools, e.g. in this case

objdump -M intel -d generic/bignum_even.o

and then you see the number:

   ....
   e:	48 83 f0 01          	xor    rax,0x1
  12:	c3                   	ret
