### ISSUE TITLE
About the code of .ml file.

### ISSUE THREAD

**Issue by ZHANGHE24** [awslabs/s2n-bignum#2]
Is there any method or idea for verifying from assembling code(machine code) to writing ml code, or what tools can be used?
And is the code language in .ml file HOL Light?
If you have free time, please help me. Thanks.

**Comment by ZHANGHE24** [comment]
Whether the verification using machine code directly is due to efficiency problems? I guess. So you don't think about implementation and verification using C.

**Comment by jargh** [comment]
The underlying language is indeed HOL Light. The "Makefile" has some explanation down in the "Proof-related parts" comment lines.

The formalized definitions can be generated automatically from the object file (on Linux/ELF at least) using the "print_literal_from_elf" function in the (HOL Light) OCaml toplevel. The right invocation is written in each .ml file in comments near the start.

Automating the full proof construction is a more difficult question. I do not believe it is likely to be possible, but the proofs could certainly be more automated than they are. Very often one can start from a related function and edit the proof to get the basic template about right.
