### ISSUE TITLE
[portability] Do not use static qualifiers for Windows build

### ISSUE THREAD

**Issue by torben-hansen** [awslabs/s2n-bignum#97]
Using static qualifiers inside arrays, [as done in the s2n-bignum header file](https://github.com/awslabs/s2n-bignum/blob/main/include/s2n-bignum.h), can aid the compiler and is specified in C99 6.7.5.3/7. But it's not portable, since mscv apparently doesn't support it. Consider whether it's worth using this feature.

This means that downstream must maintain their header files.

**Comment by torben-hansen** [comment]
See e.g. https://developercommunity.visualstudio.com/t/c11-function-declarators-not-supported/10097089

**Comment by jimgrundy** [comment]
How do we feel about #ifdefs? These kinds of qualifiers are not just meaningful to compilers, they give users an understanding of the the behavior of a routine with a degree of precision that a comment doesn't quite match.

**Comment by torben-hansen** [comment]
That would work. But you would either have to macrofy things or duplicate declarations. Or make it generative, reading assembly files, from one source of truth.

**Comment by jimgrundy** [comment]
Part of me would be happy, well, less unhappy than simply not having it, to do something as repetitive as the following (though I can also see the objection to it):

#ifdef MSVC
extern void bignum_add_p25519 (uint64_t z[/*static 4*/], uint64_t x[/*static 4*/], uint64_t y[/*static 4*/]);
#else 
extern void bignum_add_p25519 (uint64_t z[static 4], uint64_t x[static 4], uint64_t y[static 4]);
#endif

But ideally we would generate that from a single source of truth. Maybe also generate Rust extern signatures from that same source of truth one day.

**Comment by jimgrundy** [comment]
I guess I could live with just dropping the "static 4" in the interim since the generation solution seems like the ultimate way to go.

**Comment by torben-hansen** [comment]
Maybe something stupid like this can work: https://github.com/awslabs/s2n-bignum/pull/98

**Comment by aqjune-aws** [comment]
Closing this issue as resolved by the pull request.
